# Generated by Django 6.0.4 on 2026-06-26 19:15

import apps.core.models
import apps.customers.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.JSONField(default=dict)),
                ('color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('size', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sizes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', max_length=50)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.SlugField(editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('shipping_method', models.CharField(default='', max_length=50)),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pay.invoice')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(default=apps.customers.models.generate_item_id, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('properties', models.JSONField(default=dict, editable=False)),
                ('tracking_number', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('designer_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('collection_destination_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('received', 'Received'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('collection_origin_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('received', 'Received'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('customer_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('masked_email', models.EmailField(blank=True, help_text='Forwarding alias that hides the real customer email.', max_length=254, null=True)),
                ('masked_phone', models.CharField(blank=True, help_text='Masked customer phone number for designer view.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color', to='core.color')),
                ('designer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='pay.escrow')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('size', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='core.sizes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('current_status', models.CharField(default='Pending', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='customers.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('return_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong Item'), ('wrong_size', 'Wrong Size'), ('not_as_described', 'Not As Described'), ('poor_quality', 'Poor Quality'), ('missing_parts', 'Missing Parts'), ('late_delivery', 'Late Delivery'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('designer_status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('customer_status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='customers.orderitem')),
                ('packaging_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_packaging_photo', to='core.mediaasset')),
                ('product_photos', models.ManyToManyField(blank=True, related_name='return_product_photos', to='core.mediaasset')),
                ('unboxing_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_unboxing_video', to='core.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dispute_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='opened', max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('refund_approved', 'Refund Approved'), ('refund_denied', 'Refund Denied'), ('partial_refund', 'Partial Refund'), ('platform_credit', 'Platform Credit')], max_length=30, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('designer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_evidence', models.ManyToManyField(blank=True, related_name='dispute_customer_evidence', to='core.mediaasset')),
                ('designer_evidence', models.ManyToManyField(blank=True, related_name='dispute_designer_evidence', to='core.mediaasset')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='customers.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='core.product')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
