# Generated by Django 6.0.4 on 2026-06-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='packaging_approval_status',
            field=models.CharField(choices=[('unsubmitted', 'Unsubmitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unsubmitted', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_images',
            field=models.ManyToManyField(blank=True, related_name='order_packaging_images', to='core.mediaasset'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='packaging_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_packaging_video', to='core.mediaasset'),
        ),
    ]
