# Generated by Django 6.0.4 on 2026-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_orderitem_packaging_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='browse_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review_request_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
