# Generated by Django 5.2.8 on 2025-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
