# Generated by Django 5.2.8 on 2025-12-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cartitem_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
