# Generated by Django 5.2.8 on 2025-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_orderitem_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='', max_length=50),
        ),
    ]
