# Generated by Django 5.2.8 on 2026-01-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_order_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
