# Generated by Django 5.2.8 on 2026-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_order_shipping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='return_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
