# Generated by Django 5.2.8 on 2026-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_returnrequest_admin_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='designer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
