# Generated by Django 5.2.8 on 2026-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_orderitem_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
