# Generated by Django 5.2.8 on 2026-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='properties',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
