# Generated by Django 5.2.8 on 2026-02-21 08:38

import apps.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_orderitem_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(default=apps.customers.models.generate_item_id, max_length=100, null=True),
        ),
    ]
