# Generated by Django 5.2.8 on 2026-03-03 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_orderitem_designer'),
        ('pay', '0003_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='escrow',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='pay.escrow'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='designer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('refunded', 'refunded')], default='pending', max_length=20),
        ),
    ]
