# Generated by Django 5.2.8 on 2026-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_orderitem_customer_status_orderitem_escrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
