# Generated by Django 5.2.8 on 2026-03-05 13:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_unpublish_comment_product_unpublish_reasons'),
        ('customers', '0022_orderitem_delivered_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='admin_status',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='designer_status',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='packaging_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_packaging_photo', to='core.mediaasset'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='product_photos',
            field=models.ManyToManyField(blank=True, related_name='return_product_photos', to='core.mediaasset'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='unboxing_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_unboxing_video', to='core.mediaasset'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong Item'), ('wrong_size', 'Wrong Size'), ('not_as_described', 'Not As Described'), ('poor_quality', 'Poor Quality'), ('missing_parts', 'Missing Parts'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='return_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
