# Generated by Django 5.2.8 on 2026-03-05 15:02

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_alter_returnrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
