# Generated by Django 5.2.8 on 2026-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_returnrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='designer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
