# Generated by Django 5.2.8 on 2026-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_returnrequest_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
    ]
