# Generated by Django 5.2.8 on 2026-03-11 18:30

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_returnrequest_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
