# Generated by Django 5.2.8 on 2026-03-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_alter_returnrequest_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
