# Generated by Django 5.2.8 on 2026-04-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='masked_email',
            field=models.EmailField(blank=True, help_text='Forwarding alias that hides the real customer email.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='masked_phone',
            field=models.CharField(blank=True, help_text='Masked customer phone number for designer view.', max_length=50, null=True),
        ),
    ]
