# Generated by Django 5.2.8 on 2026-04-16 10:28

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_mediaasset_user'),
        ('customers', '0030_orderitem_masked_email_orderitem_masked_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='admin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='customer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='designer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('wrong_item', 'Wrong Item'), ('wrong_size', 'Wrong Size'), ('not_as_described', 'Not As Described'), ('poor_quality', 'Poor Quality'), ('missing_parts', 'Missing Parts'), ('late_delivery', 'Late Delivery'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_in_transit', 'Return In Transit'), ('return_received', 'Return Received'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('dispute_opened', 'Dispute Opened'), ('dispute_under_review', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('dispute_escalated', 'Dispute Escalated'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dispute_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='opened', max_length=30)),
                ('resolution', models.CharField(blank=True, choices=[('refund_approved', 'Refund Approved'), ('refund_denied', 'Refund Denied'), ('partial_refund', 'Partial Refund'), ('platform_credit', 'Platform Credit')], max_length=30, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('designer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_evidence', models.ManyToManyField(blank=True, related_name='dispute_customer_evidence', to='core.mediaasset')),
                ('designer_evidence', models.ManyToManyField(blank=True, related_name='dispute_designer_evidence', to='core.mediaasset')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='customers.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
