# Generated by Django 6.0.4 on 2026-06-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_returnrequest_return_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
