# Generated by Django 6.0.4 on 2026-06-27 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='assigned_agents',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
