# Generated by Django 6.0.4 on 2026-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supportticket_assigned_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_type',
            field=models.CharField(blank=True, default='ready_to_ship', max_length=100),
        ),
    ]
