# Generated by Django 5.2.8 on 2025-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_designer_product_featured_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sustainable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
