# Generated by Django 6.0.4 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productview_anon_id_productview_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('in_progress', 'In Progress'), ('investigating', 'Investigating'), ('awaiting_party', 'Awaiting Party'), ('waiting', 'Waiting on Designer'), ('decision', 'Decision'), ('action_pending', 'Action Pending'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=15),
        ),
    ]
