# Generated by Django 5.2.8 on 2025-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_is_sustainable_product_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_admin_unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
