# Generated by Django 5.2.8 on 2025-12-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='designer',
            new_name='user',
        ),
    ]
