# Generated by Django 5.2.8 on 2025-12-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_designer_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
    ]
