# Generated by Django 5.2.8 on 2026-01-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_product_color_color_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.product'),
        ),
    ]
