# Generated by Django 5.2.8 on 2026-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sizes_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
