# Generated by Django 5.2.8 on 2026-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sizes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
