# Generated by Django 5.2.8 on 2026-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_admin_unpublished',
            new_name='is_admin_published',
        ),
    ]
