# Generated by Django 5.2.8 on 2026-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_is_admin_unpublished_product_is_admin_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unpublish_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unpublish_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
