# Generated by Django 5.2.8 on 2026-03-05 15:02

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_unpublish_comment_product_unpublish_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
