# Generated by Django 6.0.4 on 2026-05-13 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_type',
            field=models.CharField(choices=[('ready_to_ship', 'Ready to Ship'), ('made_to_order', 'Made to Order'), ('pre_order', 'Pre-Order'), ('rentable', 'Rentable')], default='ready_to_ship', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregated fit feedback e.g. {"true_to_size": 87, "too_tight": 5, "too_loose": 8}'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='Lead time in days for Made-to-Order or Pre-Order items'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('work', 'Work'), ('casual', 'Casual'), ('party', 'Party'), ('traditional', 'Traditional'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='print_type',
            field=models.CharField(blank=True, choices=[('ankara', 'Ankara'), ('adire', 'Adire'), ('kente', 'Kente'), ('bogolan', 'Bogolan'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rental price for rentable items', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='sustainability_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
