# Generated by Django 6.0.4 on 2026-05-13 10:40

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_availability_type_product_country_of_origin_and_more'),
        ('customers', '0031_returnrequest_return_tracking_number_and_more'),
        ('designers', '0017_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_earned', models.IntegerField(default=0)),
                ('lifetime_redeemed', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expire')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='customers.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('collection_type', models.CharField(choices=[('curated', 'Curated'), ('trending', 'Trending'), ('seasonal', 'Seasonal'), ('occasion', 'Occasion'), ('print', 'Print Style')], default='curated', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='smart_collections/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, related_name='smart_collections', to='core.product')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignerDailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('add_to_cart_events', models.PositiveIntegerField(default=0)),
                ('purchase_events', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='designers.designer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('designer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event_type', models.CharField(default='product_view', max_length=50)),
                ('source', models.CharField(blank=True, default='organic', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_view_events', to='designers.designer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['designer', 'created_at'], name='core_produc_designe_9b439e_idx'), models.Index(fields=['product', 'created_at'], name='core_produc_product_3b9813_idx')],
            },
        ),
    ]
