# Generated by Django 6.0.4 on 2026-05-14 11:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_loyaltybalance_loyaltypoints_smartcollection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart_image',
            field=models.ImageField(blank=True, help_text='Upload a size chart image for this product', null=True, upload_to='product_size_charts/'),
        ),
        migrations.AddField(
            model_name='review',
            name='fit_feedback',
            field=models.CharField(blank=True, choices=[('perfect_fit', 'Perfect fit'), ('true_to_size', 'True to size'), ('too_tight', 'Too tight'), ('too_loose', 'Too loose'), ('runs_large', 'Runs large')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserLookbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Lookbook title', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='lookbooks/')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, related_name='lookbooks', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_size', models.CharField(help_text='Recommended size name', max_length=50)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0, help_text='0-100 confidence %', validators=[django.core.validators.MinValueValidator(0)])),
                ('body_measurements', models.JSONField(blank=True, default=dict, help_text='{"chest": 96, "waist": 82, "hips": 100}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendations', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
