# Generated by Django 6.0.4 on 2026-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_product_size_chart_image_review_fit_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fit_me_image',
            field=models.ImageField(blank=True, help_text='PNG image with transparent background for AI virtual try-on', null=True, upload_to='product_fitme_images/'),
        ),
    ]
