# Generated by Django 6.0.4 on 2026-05-18 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_seed_standard_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollection',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='True if created by AI mode'),
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='query',
            field=models.CharField(blank=True, help_text='Query string used to generate this collection', max_length=300),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector embedding (list of floats) for semantic search')),
                ('embedding_text', models.TextField(blank=True, help_text='Concatenated text used to generate the embedding')),
                ('dimensions', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.product')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes only visible to staff')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
