# Generated by Django 6.0.4 on 2026-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fit_me_image',
            field=models.ImageField(blank=True, help_text='PNG with alpha transparency (transparent background) for AI FitMe. Best results: front-facing garment, unworn, clean edges, portrait orientation for dresses/tops, landscape for accessories. Minimum 512px on short edge.', null=True, upload_to='product_fitme_images/'),
        ),
    ]
