# Generated by Django 6.0.4 on 2026-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_product_fit_me_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
