# Generated by Django 6.0.4 on 2026-06-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_m2m', to='core.category'),
        ),
    ]
