# Generated by Django 6.0.4 on 2026-06-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Package height in centimeters (cm)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Package length in centimeters (cm)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Product weight in kilograms (kg)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Package width in centimeters (cm)', max_digits=6),
        ),
    ]
