# Generated by Django 6.0.4 on 2026-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='applicable_countries',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO country codes this method applies to. Empty = global.'),
        ),
    ]
