# Generated by Django 6.0.4 on 2026-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_shippingmethod_applicable_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('style_seeker', 'Style Seeker'), ('style_icon', 'Style Icon'), ('couture', 'Couture')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
