# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_subscriptionplan_tier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiQueryCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("raw_query", models.TextField()),
                ("parsed_filters", models.JSONField(default=dict)),
                (
                    "product_ids",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of product UUID strings",
                    ),
                ),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("hit_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-hit_count", "-updated_at"],
            },
        ),
    ]
