# Generated by Django 6.0.4 on 2026-05-06 15:37

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0022_mediaasset_user'),
        ('designers', '0016_designer_lookbook_files'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmConfig',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, unique=True)),
                ('market_stage', models.CharField(choices=[('early', 'Early'), ('growth', 'Growth'), ('scale', 'Scale')], default='growth', max_length=10)),
                ('weight_engagement', models.FloatField(default=0.2)),
                ('weight_conversion', models.FloatField(default=0.4)),
                ('weight_retention', models.FloatField(default=0.1)),
                ('weight_freshness', models.FloatField(default=0.15)),
                ('weight_designer', models.FloatField(default=0.1)),
                ('weight_fit', models.FloatField(default=0.05)),
                ('exploration_ratio', models.FloatField(default=0.25)),
                ('new_product_boost_days', models.PositiveIntegerField(default=7)),
                ('trending_sigma_threshold', models.FloatField(default=2.0)),
                ('trend_window_hours', models.PositiveIntegerField(default=48)),
            ],
            options={
                'verbose_name': 'Algorithm Configuration',
                'verbose_name_plural': 'Algorithm Configurations',
            },
        ),
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('anomaly_type', models.CharField(choices=[('rapid_clicks', 'Rapid Sequential Clicks'), ('review_burst', 'Review Burst'), ('bot_pattern', 'Bot-Like Pattern'), ('rating_manipulation', 'Rating Manipulation')], max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('score_suppressed', models.BooleanField(default=False)),
                ('suppression_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBalance',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('demand_score', models.FloatField(default=0)),
                ('supply_score', models.FloatField(default=0)),
                ('saturation_index', models.FloatField(default=1.0)),
                ('exposure_multiplier', models.FloatField(default=1.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='core.category')),
            ],
            options={
                'ordering': ['-saturation_index'],
            },
        ),
        migrations.CreateModel(
            name='DesignerScore',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_speed_score', models.FloatField(default=0.5)),
                ('fulfillment_rate_score', models.FloatField(default=0.5)),
                ('customer_rating_score', models.FloatField(default=0.5)),
                ('responsiveness_score', models.FloatField(default=0.5)),
                ('operational_score', models.FloatField(default=0.5)),
                ('sales_growth_mom', models.FloatField(default=0)),
                ('inventory_stability', models.FloatField(default=0.5)),
                ('content_quality', models.FloatField(default=0.5)),
                ('responsiveness_trend', models.FloatField(default=0)),
                ('business_health_score', models.FloatField(default=0.5)),
                ('lifecycle_stage', models.CharField(choices=[('new', 'New'), ('growing', 'Growing'), ('top', 'Top')], default='new', max_length=20)),
                ('penalty_multiplier', models.FloatField(default=1.0)),
                ('penalty_reason', models.JSONField(blank=True, default=list)),
                ('penalty_expires_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='designers.designer')),
            ],
            options={
                'ordering': ['-business_health_score'],
            },
        ),
        migrations.CreateModel(
            name='SessionIntent',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('product_depth_views', models.PositiveIntegerField(default=0)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('first_action_at', models.DateTimeField(auto_now_add=True)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('intent_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_action_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceProfile',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_affinity', models.JSONField(default=dict)),
                ('preferred_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_responsiveness', models.FloatField(default=0.5)),
                ('size_profile', models.JSONField(default=dict)),
                ('cultural_affinity', models.JSONField(default=dict)),
                ('sessions_per_week', models.FloatField(default=0)),
                ('avg_session_duration_seconds', models.FloatField(default=0)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('conversion_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('retention_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('freshness_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('designer_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fit_confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('urbana_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('trend_score', models.FloatField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('exploration_weight', models.FloatField(default=0.1)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urbana_score', to='core.product')),
            ],
            options={
                'ordering': ['-urbana_score'],
                'indexes': [models.Index(fields=['urbana_score', 'computed_at'], name='algorithm_p_urbana__83207c_idx'), models.Index(fields=['is_trending', 'trend_score'], name='algorithm_p_is_tren_ef305a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductTrendSnapshot',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hour', models.DateTimeField(db_index=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='core.product')),
            ],
            options={
                'ordering': ['-hour'],
                'unique_together': {('product', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('product_click', 'Product Click'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('wishlist_add', 'Wishlist Add'), ('wishlist_remove', 'Wishlist Remove'), ('purchase', 'Purchase'), ('search', 'Search Query'), ('scroll_depth', 'Scroll Depth'), ('price_filter', 'Price Filter'), ('category_browse', 'Category Browse'), ('time_on_product', 'Time on Product'), ('review_view', 'Review View'), ('story_view', 'Story View'), ('share', 'Share'), ('return_initiated', 'Return Initiated')], db_index=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='designers.designer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='algorithm_u_user_id_6d7099_idx'), models.Index(fields=['session_id', 'created_at'], name='algorithm_u_session_4e3f2f_idx'), models.Index(fields=['product', 'event_type', 'created_at'], name='algorithm_u_product_854008_idx')],
            },
        ),
    ]
