# Generated by Django 6.0.4 on 2026-06-26 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('algorithm', '0002_initial'),
        ('core', '0001_initial'),
        ('designers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorybalance',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='core.category'),
        ),
        migrations.AddField(
            model_name='designerscore',
            name='designer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='designers.designer'),
        ),
        migrations.AddField(
            model_name='productscore',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urbana_score', to='core.product'),
        ),
        migrations.AddField(
            model_name='producttrendsnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='core.product'),
        ),
        migrations.AddField(
            model_name='sessionintent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='designers.designer'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.product'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferenceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productscore',
            index=models.Index(fields=['urbana_score', 'computed_at'], name='algorithm_p_urbana__83207c_idx'),
        ),
        migrations.AddIndex(
            model_name='productscore',
            index=models.Index(fields=['is_trending', 'trend_score'], name='algorithm_p_is_tren_ef305a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producttrendsnapshot',
            unique_together={('product', 'hour')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='algorithm_u_user_id_6d7099_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['session_id', 'created_at'], name='algorithm_u_session_4e3f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['product', 'event_type', 'created_at'], name='algorithm_u_product_854008_idx'),
        ),
    ]
