# Generated by Django 6.0.4 on 2026-08-09 17:04

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('manual', 'Manual')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
            },
        ),
        migrations.CreateModel(
            name='LaunchCampaign',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('preview_text', models.CharField(blank=True, default='', max_length=150)),
                ('segment_query', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Launch Campaign',
                'verbose_name_plural': 'Launch Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaunchConfig',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('gate_enabled', models.BooleanField(default=False)),
                ('capture_mode', models.CharField(choices=[('email_only', 'Email only')], default='email_only', max_length=20)),
                ('headline', models.CharField(default='African fashion is launching soon.', max_length=255)),
                ('subhead', models.CharField(default='Be the first to discover and shop designs from African creators.', max_length=255)),
                ('cta_label', models.CharField(default='Get early access', max_length=100)),
                ('trust_line', models.CharField(default="We'll email you once at launch. Nothing else.", max_length=255)),
                ('hero_image_path', models.CharField(default='/cat_dresses.png', max_length=255)),
                ('hero_image_alt', models.CharField(default='African fashion dresses', max_length=255)),
                ('show_signup_counter', models.BooleanField(default=True)),
                ('counter_offset', models.PositiveIntegerField(default=0)),
                ('referral_enabled', models.BooleanField(default=True)),
                ('referral_spots_per_ref', models.PositiveSmallIntegerField(default=10)),
                ('double_optin_enabled', models.BooleanField(default=True)),
                ('designer_cta_enabled', models.BooleanField(default=True)),
                ('designer_cta_label', models.CharField(default='Are you a designer? Apply to sell on Urbana', max_length=255)),
                ('designer_cta_url', models.URLField(default='https://designer.urbanaafrica.com')),
                ('allowed_paths', models.JSONField(blank=True, default=list)),
                ('consent_text', models.TextField(default='I want to be notified by email when Urbana launches and agree to the Privacy Policy.')),
                ('consent_version', models.CharField(default='1.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Launch Config',
                'verbose_name_plural': 'Launch Config',
            },
        ),
        migrations.CreateModel(
            name='WaitlistSubscriber',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('interests', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('converted', 'Converted')], db_index=True, default='pending', max_length=20)),
                ('confirm_token', models.CharField(blank=True, default='', max_length=128)),
                ('confirm_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.PositiveIntegerField(db_index=True, unique=True)),
                ('referral_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('spots_skipped', models.PositiveIntegerField(default=0)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_version', models.CharField(blank=True, default='', max_length=20)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('medium', models.CharField(blank=True, default='', max_length=100)),
                ('campaign', models.CharField(blank=True, default='', max_length=100)),
                ('term', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=100)),
                ('landing_path', models.CharField(blank=True, default='', max_length=255)),
                ('referrer_url', models.URLField(blank=True, default='')),
                ('anon_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('returned_after_email_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('first_order_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='launch.waitlistsubscriber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waitlist Subscriber',
                'verbose_name_plural': 'Waitlist Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEvent',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('confirm_email_sent', 'Confirm Email Sent'), ('confirmed', 'Confirmed'), ('referral_shared', 'Referral Shared'), ('referred_signup', 'Referred Signup'), ('email_sent', 'Email Sent'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('returned_to_site', 'Returned to Site'), ('designer_cta_clicked', 'Designer CTA Clicked'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('converted', 'Converted')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='launch.launchcampaign')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='launch.waitlistsubscriber')),
            ],
            options={
                'verbose_name': 'Waitlist Event',
                'verbose_name_plural': 'Waitlist Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='waitlistsubscriber',
            index=models.Index(fields=['status', 'created_at'], name='launch_wait_status_bb2d00_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistsubscriber',
            index=models.Index(fields=['anon_id', 'created_at'], name='launch_wait_anon_id_6cbefc_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistsubscriber',
            index=models.Index(fields=['referral_code'], name='launch_wait_referra_5eae94_idx'),
        ),
    ]
