# Generated by Django 6.0.4 on 2026-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchconfig',
            name='hero_image_path',
            field=models.CharField(default='/images/dresses.jpg', max_length=255),
        ),
    ]
