# Generated by Django 6.0.4 on 2026-06-26 19:15

import apps.utils.uuid_generator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerLead',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('designer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('followers_count', models.IntegerField(blank=True, default=0, null=True)),
                ('category_tags', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('Discovered', 'Discovered'), ('Contacted', 'Contacted'), ('In Discussion', 'In Discussion'), ('Signed Up', 'Signed Up'), ('Rejected', 'Rejected')], default='Discovered', max_length=50)),
                ('source', models.CharField(blank=True, help_text='e.g., Instagram API, Web Scraper', max_length=100, null=True)),
                ('date_discovered', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('target_leads', models.ManyToManyField(related_name='campaigns', to='marketing.designerlead')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Opened', 'Opened')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.designerlead')),
            ],
        ),
    ]
