# Generated by Django 6.0.4 on 2026-08-09 17:20

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.URLField()),
                ('provider_name', models.CharField(max_length=50)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('stale_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeProviderConfig',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Provider key, e.g. dataforseo', max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='API keys, zones, actor IDs')),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('cost_per_1k_credits', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadSuppression',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('brand_name', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500)),
                ('provider_name', models.CharField(blank=True, default='', max_length=50)),
                ('max_results', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeCall',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
                ('call_type', models.CharField(choices=[('search', 'Search'), ('extract', 'Extract')], max_length=20)),
                ('input_url', models.URLField(blank=True, default='')),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='marketing.scrapejob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadEnrichment',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('raw_html', models.TextField(blank=True, default='')),
                ('extraction_source', models.CharField(blank=True, default='', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('enrichment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='marketing.designerlead')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichments', to='marketing.scrapejob')),
            ],
        ),
    ]
