# Generated by Django 6.0.4 on 2026-08-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_scrapecache_scrapeproviderconfig_leadsuppression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('budget_stopped', 'Budget Stopped')], default='queued', max_length=20),
        ),
    ]
