# Generated by Django 6.0.4 on 2026-10-05 10:36

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_scrapeproviderconfig_monthly_spend_4dp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='designerlead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_designer_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designerlead',
            name='qualification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='designerlead',
            name='qualification_type',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('direct_designer', 'Direct Designer'), ('directory', 'Directory'), ('community', 'Community / Group'), ('aggregator', 'Aggregator / Ranking'), ('agency', 'Agency'), ('generic_account', 'Generic Account'), ('uncertain', 'Uncertain'), ('not_a_lead', 'Not a Lead')], db_index=True, default='unclassified', max_length=30),
        ),
        migrations.AddField(
            model_name='designerlead',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='audience_filter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='send_cap',
            field=models.PositiveIntegerField(default=0, help_text='Maximum successful sends. 0 = no cap.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sending', 'Sending'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leadsuppression',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_suppressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadsuppression',
            name='handle',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='designerlead',
            name='status',
            field=models.CharField(choices=[('Discovered', 'Discovered'), ('Needs Review', 'Needs Review'), ('Qualified', 'Qualified'), ('Assigned', 'Assigned'), ('Contacted', 'Contacted'), ('Replied', 'Replied'), ('Meeting', 'Meeting'), ('Applied', 'Applied'), ('Approved', 'Approved'), ('Activated', 'Activated'), ('In Discussion', 'In Discussion'), ('Signed Up', 'Signed Up'), ('Rejected', 'Rejected'), ('Suppressed', 'Suppressed')], default='Discovered', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='target_leads',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='marketing.designerlead'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Opened', 'Opened'), ('Suppressed', 'Suppressed'), ('Skipped', 'Skipped')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leadsuppression',
            name='reason',
            field=models.CharField(choices=[('manual', 'Manual'), ('unsubscribe', 'Unsubscribe'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('rejected', 'Rejected'), ('request', 'Data Subject Request')], default='manual', max_length=50),
        ),
        migrations.CreateModel(
            name='LeadQualificationDecision',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, default='', max_length=255)),
                ('candidate_url', models.URLField(blank=True, default='')),
                ('decision', models.CharField(choices=[('direct_designer', 'Direct Designer'), ('directory', 'Directory'), ('community', 'Community / Group'), ('aggregator', 'Aggregator / Ranking'), ('agency', 'Agency'), ('generic_account', 'Generic Account'), ('uncertain', 'Uncertain'), ('not_a_lead', 'Not a Lead'), ('qualified', 'Qualified (human)'), ('rejected', 'Rejected (human)'), ('suppressed', 'Suppressed (human)'), ('merged', 'Merged (human)')], max_length=30)),
                ('decided_by', models.CharField(choices=[('rules', 'Rule classifier'), ('llm', 'LLM'), ('human', 'Human')], max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_qualification_decisions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_decisions', to='marketing.scrapejob')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_decisions', to='marketing.designerlead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
