# Generated by Django 6.0.4 on 2026-10-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_designerlead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerlead',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Set when this duplicate was consolidated into another lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='marketing.designerlead'),
        ),
    ]
