# Generated by Django 6.0.4 on 2026-06-26 19:15

import apps.utils.uuid_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.FileField(blank=True, max_length=10, upload_to='banks/logos/')),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('processor', models.CharField(max_length=50)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('status_code', models.IntegerField(default=200)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='NG', max_length=5)),
                ('account_type', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paystack', 'Paystack')], default='flutterwave', max_length=20)),
                ('recipient_code', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Detail',
                'verbose_name_plural': 'Account Details',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20)),
                ('processor_payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('date_time_paid', models.DateTimeField(blank=True, null=True)),
                ('date_time_approved', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date_time_added'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCommisions',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='No Comment', max_length=500)),
                ('purpose', models.CharField(blank=True, default='', max_length=500)),
                ('service', models.CharField(blank=True, default='', max_length=500)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
            ],
            options={
                'db_table': 'partnercommisions',
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_auto_released', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='held', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_escrows', to=settings.AUTH_USER_MODEL)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_escrows', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.payment')),
            ],
            options={
                'db_table': 'escrows',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20)),
                ('processor_payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='Invoice', max_length=200)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expire_notification_sent', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
                ('payment_attempts', models.ManyToManyField(blank=True, related_name='invoices', to='pay.paymentattempt')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('transfer_ref', models.CharField(blank=True, default='', max_length=100)),
                ('transfer_id', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(blank=True, default='status', max_length=500)),
                ('bank_code', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=500)),
                ('account_name', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_code', models.CharField(blank=True, default='', max_length=200)),
                ('delete_reason', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('withdrawal', 'Withdrawal'), ('commission', 'Platform Commission'), ('refund', 'Refund')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('related_order_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pay.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payout_currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('flutterwave_transfer_id', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.wallet')),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'transaction_type'], name='pay_transac_user_id_ab6f91_idx'), models.Index(fields=['status'], name='pay_transac_status_a1c428_idx')],
            },
        ),
    ]
