# Generated by Django 5.2.7 on 2025-11-01 10:41

import apps.utils.uuid_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('code', models.CharField(blank=True, default='', max_length=200)),
                ('logo', models.FileField(blank=True, max_length=10, upload_to='banks/logos/')),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('processor', models.CharField(max_length=50)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('status_code', models.IntegerField(default=200)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20)),
                ('processor_payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(blank=True, default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('date_time_paid', models.DateTimeField(blank=True, null=True)),
                ('date_time_approved', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-date_time_added'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCommisions',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, default='No Comment', max_length=500)),
                ('purpose', models.CharField(blank=True, default='', max_length=500)),
                ('service', models.CharField(blank=True, default='', max_length=500)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
            ],
            options={
                'db_table': 'partnercommisions',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, choices=[('paystack', 'Paystack'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20)),
                ('processor_payment_id', models.CharField(blank=True, default='', max_length=200)),
                ('currency', models.CharField(blank=True, default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=50)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('purpose', models.CharField(default='Invoice', max_length=200)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expire_notification_sent', models.BooleanField(default=False)),
                ('date_time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
                ('payment_attempts', models.ManyToManyField(blank=True, related_name='invoices', to='pay.paymentattempt')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('transfer_ref', models.CharField(blank=True, default='', max_length=100)),
                ('transfer_id', models.CharField(blank=True, default='', max_length=100)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(blank=True, default='status', max_length=500)),
                ('bank_code', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=500)),
                ('account_name', models.CharField(blank=True, default='', max_length=500)),
                ('recipient_code', models.CharField(blank=True, default='', max_length=200)),
                ('delete_reason', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('date_time_added', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
    ]
