# Generated by Django 6.0.4 on 2026-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_alter_accountdetail_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='processor',
            field=models.CharField(blank=True, choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='processor',
            field=models.CharField(blank=True, choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='', max_length=20),
        ),
    ]
