# Generated by Django 6.0.4 on 2026-09-14 13:14

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_alter_payment_processor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorFee',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('processor', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20)),
                ('percentage_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('fixed_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_fee', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_fees', to='pay.payment')),
            ],
            options={
                'db_table': 'processor_fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiCostRecord',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, default='', help_text='Anonymous session ID when user is not authenticated', max_length=100)),
                ('service', models.CharField(help_text="e.g. 'ai_search', 'ai_tryon', 'ai_fitme'", max_length=50)),
                ('provider', models.CharField(help_text="e.g. 'gemini', 'fal', 'replicate'", max_length=50)),
                ('model', models.CharField(blank=True, default='', help_text="e.g. 'gemini-2.5-flash-image-preview'", max_length=100)),
                ('units', models.CharField(default='1', help_text="e.g. '1', '1500_tokens', '1_image'", max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('related_request_id', models.CharField(blank=True, default='', max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_cost_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_cost_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service'], name='api_cost_re_user_id_6c5443_idx'), models.Index(fields=['service', 'provider'], name='api_cost_re_service_2430a5_idx'), models.Index(fields=['created_at'], name='api_cost_re_created_416fb7_idx')],
            },
        ),
    ]
