# Generated by Django 5.2.8 on 2026-03-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_escrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrow',
            old_name='order_id',
            new_name='order_item_id',
        ),
    ]
