# Generated by Django 6.0.4 on 2026-09-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_add_api_cost_and_processor_fee_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('commission', 'Platform Commission'), ('refund', 'Refund')], max_length=50),
        ),
    ]
