# Generated by Django 5.2.8 on 2026-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_rename_order_id_escrow_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='is_auto_released',
            field=models.BooleanField(default=False),
        ),
    ]
