# Generated by Django 5.2.8 on 2026-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='order_item_id',
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='held', max_length=50),
        ),
    ]
