# Generated by Django 5.2.8 on 2026-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_remove_escrow_order_item_id_alter_escrow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payout_amount_ngn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
