# Generated by Django 5.2.8 on 2026-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_withdrawal_payout_amount_ngn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='payout_amount_ngn',
            new_name='payout_amount',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
    ]
