# Generated by Django 5.2.8 on 2026-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_rename_payout_amount_ngn_withdrawal_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
