# Generated by Django 6.0.4 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_withdrawal_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='account_type',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], default='flutterwave', max_length=20),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='country',
            field=models.CharField(blank=True, default='NG', max_length=5),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
