# Generated by Django 6.0.4 on 2026-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_account_detail_type_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
    ]
