# Generated by Django 6.0.4 on 2026-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0013_alter_withdrawal_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account_type',
            field=models.CharField(choices=[('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('paystack', 'Paystack')], default='flutterwave', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
