# Generated by Django 6.0.4 on 2026-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_alter_accountdetail_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='payout_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
