# Generated by Django 6.0.4 on 2026-10-05 12:21

import apps.utils.uuid_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('queue', models.CharField(choices=[('order_pending', 'Order — unacknowledged'), ('dispatch_late', 'Order — late to dispatch'), ('delivery_exception', 'Delivery exception'), ('support_case', 'Support case'), ('designer_onboarding', 'Designer onboarding'), ('catalog_moderation', 'Catalog moderation'), ('reconciliation', 'Reconciliation exception'), ('payout_approval', 'Payout approval')], db_index=True, max_length=40)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Snapshot evidence — order id, amount, age, source status.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalated', models.BooleanField(default=False)),
                ('source_status', models.CharField(blank=True, default='', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_work_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'queue', 'due_at'], name='administrat_status_6b38b0_idx'), models.Index(fields=['assigned_to', 'status'], name='administrat_assigne_390d16_idx')],
                'constraints': [models.UniqueConstraint(fields=('queue', 'entity_type', 'entity_id'), name='unique_work_item_per_source')],
            },
        ),
    ]
