# Generated by Django 6.0.4 on 2026-10-05 14:42

import apps.utils.uuid_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_workitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Capability-style action key, e.g. 'finance.payout_settled'.", max_length=60)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of the action inputs the approver is signing off on.')),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('action', 'entity_type', 'entity_id'), name='unique_pending_approval_per_action')],
            },
        ),
    ]
