# Generated by Django 6.0.4 on 2026-10-05 16:34

import apps.utils.uuid_generator
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_approvalrequest'),
        ('core', '0006_alter_supportticket_status'),
        ('customers', '0003_customer_browse_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='escalated_reason',
            field=models.CharField(blank=True, default='', help_text="Rule that escalated the item (SUP-04) — e.g. 'sla_breach'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='queue',
            field=models.CharField(choices=[('order_pending', 'Order — unacknowledged'), ('dispatch_late', 'Order — late to dispatch'), ('delivery_exception', 'Delivery exception'), ('support_case', 'Support case'), ('designer_onboarding', 'Designer onboarding'), ('catalog_moderation', 'Catalog moderation'), ('reconciliation', 'Reconciliation exception'), ('payout_approval', 'Payout approval'), ('return_action', 'Return awaiting action'), ('incident', 'Incident')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('sev1', 'SEV-1 — critical'), ('sev2', 'SEV-2 — major'), ('sev3', 'SEV-3 — minor'), ('sev4', 'SEV-4 — cosmetic')], db_index=True, default='sev3', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('postmortem', 'Postmortem'), ('closed', 'Closed')], db_index=True, default='open', max_length=15)),
                ('summary', models.TextField(blank=True, default='')),
                ('customer_impact', models.TextField(blank=True, default='')),
                ('timeline', models.JSONField(blank=True, default=list, help_text="Chronological entries: [{'at': ts, 'by': email, 'note'}].")),
                ('mitigations', models.TextField(blank=True, default='')),
                ('communications', models.TextField(blank=True, default='')),
                ('postmortem', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('access', 'Access / export'), ('correction', 'Correction'), ('deletion', 'Deletion'), ('objection', 'Marketing objection')], max_length=20)),
                ('subject_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verifying', 'Verifying identity'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='received', max_length=15)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_exception', models.TextField(blank=True, default='', help_text='Lawful retention basis when deletion cannot fully propagate (e.g. financial records).')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityGrant',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('capability', models.CharField(db_index=True, max_length=60)),
                ('granted', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Break-glass expiry — null means permanent.', null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capability_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'capability'), name='unique_active_grant_per_capability')],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('case_ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ticket', 'Ticket'), ('return', 'Return'), ('dispute', 'Dispute'), ('payment_claim', 'Payment claim'), ('delivery_complaint', 'Delivery complaint'), ('general', 'General')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('in_progress', 'In Progress'), ('investigating', 'Investigating'), ('awaiting_party', 'Awaiting Party'), ('waiting', 'Waiting'), ('decision', 'Decision'), ('action_pending', 'Action Pending'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('related_links', models.JSONField(blank=True, default=list, help_text="Additional entity links: [{'type': 'Order', 'id': '…'}].")),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designer_cases', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='customers.dispute')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='customers.order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='customers.returnrequest')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='core.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category', 'owner'], name='administrat_status_db47c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField()),
                ('value', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rolled_back', 'Rolled back'), ('retired', 'Retired')], db_index=True, default='draft', max_length=15)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('high', 'High')], default='low', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_policy_version')],
            },
        ),
    ]
