# Generated by Django 6.0.4 on 2026-08-09 18:17

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortSnapshot',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cohort Snapshot',
                'verbose_name_plural': 'Cohort Snapshots',
            },
        ),
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dead Letter Event',
                'verbose_name_plural': 'Dead Letter Events',
            },
        ),
        migrations.CreateModel(
            name='FunnelSnapshot',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funnel Snapshot',
                'verbose_name_plural': 'Funnel Snapshots',
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('formula', models.TextField()),
                ('grain', models.CharField(default='daily', max_length=50)),
                ('window', models.CharField(default='30d', max_length=50)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('is_input_metric', models.BooleanField(default=False)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('source_table', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric Definition',
                'verbose_name_plural': 'Metric Definitions',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('dimension_key', models.CharField(blank=True, default='', max_length=100)),
                ('dimension_value', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'indexes': [models.Index(fields=['metric_name', 'date'], name='analytics_d_metric__3d9b4e_idx')],
                'unique_together': {('date', 'metric_name', 'dimension_key', 'dimension_value')},
            },
        ),
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('required_params', models.JSONField(blank=True, default=list)),
                ('optional_params', models.JSONField(blank=True, default=list)),
                ('pii_params', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Schema',
                'verbose_name_plural': 'Event Schemas',
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('anon_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('first_utm', models.JSONField(blank=True, default=dict)),
                ('last_utm', models.JSONField(blank=True, default=dict)),
                ('first_landing_path', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='MetricAlert',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('rule', models.CharField(choices=[('z_score', 'Z-Score'), ('threshold', 'Threshold'), ('pct_change', 'Percent Change')], max_length=20)),
                ('window', models.CharField(default='1h', max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack')], max_length=20)),
                ('threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.metricdefinition')),
            ],
            options={
                'verbose_name': 'Metric Alert',
                'verbose_name_plural': 'Metric Alerts',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('schema_version', models.CharField(default='1.0', max_length=10)),
                ('anon_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('customer_app', 'Customer App'), ('designer_app', 'Designer App'), ('admin', 'Admin'), ('server', 'Server'), ('webhook', 'Webhook'), ('mobile', 'Mobile')], default='web', max_length=20)),
                ('page_path', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.URLField(blank=True, default='')),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('utm_content', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('consent_analytics', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalid_reason', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['name', 'received_at'], name='analytics_e_name_7498c2_idx'), models.Index(fields=['anon_id', 'received_at'], name='analytics_e_anon_id_4b3789_idx'), models.Index(fields=['session_id', 'received_at'], name='analytics_e_session_591ced_idx'), models.Index(fields=['transaction_id', 'received_at'], name='analytics_e_transac_55c27d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('anon_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('pageview_count', models.PositiveIntegerField(default=0)),
                ('entry_path', models.CharField(blank=True, default='', max_length=500)),
                ('exit_path', models.CharField(blank=True, default='', max_length=500)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('converted', models.BooleanField(default=False)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'indexes': [models.Index(fields=['anon_id', 'started_at'], name='analytics_s_anon_id_07523c_idx')],
            },
        ),
    ]
