# Generated by Django 6.0.4 on 2026-09-16 12:47

import apps.utils.uuid_generator
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(db_index=True, max_length=16)),
                ('path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='analytics_p_path_33d66e_idx'), models.Index(fields=['source', '-created_at'], name='analytics_p_source_bf543f_idx'), models.Index(fields=['session_hash', '-created_at'], name='analytics_p_session_ad3451_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorEvent',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='custom', max_length=50)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('device', models.CharField(default='desktop', max_length=10)),
                ('source', models.CharField(default='web', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Visitor Event',
                'verbose_name_plural': 'Visitor Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', '-created_at'], name='analytics_v_name_4ca90e_idx'), models.Index(fields=['source', '-created_at'], name='analytics_v_source_e932c3_idx'), models.Index(fields=['session_hash', '-created_at'], name='analytics_v_session_40a85b_idx'), models.Index(fields=['category', '-created_at'], name='analytics_v_categor_1ec9e3_idx')],
            },
        ),
    ]
