# Generated by Django 6.0.4 on 2026-06-26 19:15

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='designer_collections/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('specialty', models.JSONField(blank=True, default=list, help_text='List of fashion niches e.g. ["womenswear", "menswear", "accessories"]')),
                ('country', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(blank=True, default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='designer_profiles/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='designer_profiles/')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('tagline', models.CharField(blank=True, help_text='Short brand tagline', max_length=255)),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text='{"facebook": "url", "twitter": "url", "tiktok": "url"}')),
                ('is_sustainable', models.BooleanField(default=False)),
                ('sustainability_notes', models.TextField(blank=True, help_text='Free-form notes about sustainability practices')),
                ('sustainability_certifications', models.JSONField(blank=True, default=list, help_text='List of certifications e.g. ["GOTS", "Fair Trade"]')),
                ('founder_name', models.CharField(blank=True, help_text='Designer or founder name', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Phone / WhatsApp number', max_length=50)),
                ('city', models.CharField(blank=True, help_text='City / base of operation', max_length=200)),
                ('unique_attributes', models.JSONField(blank=True, default=list, help_text='Brand uniqueness checkboxes e.g. ["handmade", "sustainable"]')),
                ('product_count_range', models.CharField(blank=True, help_text='Products ready to list: 1-5, 6-10, 11-25, 25+', max_length=50)),
                ('price_range', models.CharField(blank=True, help_text='Average product price range', max_length=50)),
                ('production_type', models.CharField(blank=True, help_text='Ready-to-wear, made-to-order, custom orders, pre-order, mix', max_length=100)),
                ('ships_internationally', models.CharField(blank=True, help_text='Yes, No, Not yet but I want to', max_length=50)),
                ('local_shipping_fee', models.DecimalField(decimal_places=2, default=0.0, help_text="Local shipping fee for domestic orders in designer's country", max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('status_reasons', models.JSONField(blank=True, default=list)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('welcome_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('upload_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('storefront_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('featured_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_designer', to='designers.collection')),
                ('lookbook_files', models.ManyToManyField(to='core.mediaasset')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='designers.designer'),
        ),
        migrations.CreateModel(
            name='DesignerAnalytics',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='designers.designer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignerOrder',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignerProduct',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='designers.designer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_product', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignerStory',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('media', models.FileField(upload_to='designer_stories/')),
                ('caption', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='designers.designer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('notified', models.BooleanField(default=False)),
                ('designer_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alert', to='designers.designerproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order', 'Order'), ('product', 'Product'), ('profile', 'Profile'), ('payout', 'Payout'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='designers.designer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=100)),
                ('tracking_status', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='customers.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='designers.designerorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='designers.designer')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='designerorder',
            name='shipping_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designers.shippingoption'),
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='designers.designerstory')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'unique_together': {('story', 'viewer')},
            },
        ),
    ]
