# Generated by Django 5.2.8 on 2025-12-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_order_shipping_amount_order_shipping_method'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerorder',
            name='product',
        ),
        migrations.AddField(
            model_name='designerorder',
            name='order_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.orderitem'),
        ),
    ]
