# Generated by Django 6.0.4 on 2026-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_availability_type'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applies_to',
            field=models.CharField(choices=[('all', 'All Products'), ('specific', 'Specific Products')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='core.product'),
        ),
    ]
