# Generated by Django 6.0.4 on 2026-06-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_promotion_applies_to_promotion_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='local_shipping_fee',
        ),
    ]
