# Generated by Django 5.2.8 on 2025-12-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0003_alter_designerorder_designer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designerorder',
            old_name='designer',
            new_name='user',
        ),
    ]
