# Generated by Django 6.0.4 on 2026-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_designer_final_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='final_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Last-chance 7-day reminder for designers who still haven't uploaded a product", null=True),
        ),
    ]
