# Generated by Django 5.2.8 on 2025-12-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_rename_designer_designerorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
