# Generated by Django 6.0.4 on 2026-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_alter_designer_final_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='health_override',
            field=models.JSONField(blank=True, default=dict, help_text='Override record: score, reason, expires_at, set_by.'),
        ),
        migrations.AddField(
            model_name='designer',
            name='suspension',
            field=models.JSONField(blank=True, default=dict, help_text='Active suspension record: reason, risk_category, set_by, set_at, review_date, notice.'),
        ),
    ]
