# Generated by Django 5.2.8 on 2025-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0005_alter_designerorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
