# Generated by Django 5.2.8 on 2026-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0006_alter_designerorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='brand_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='designer',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='story',
            field=models.TextField(blank=True),
        ),
    ]
