# Generated by Django 5.2.8 on 2026-02-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0007_designer_brand_name_designer_country_designer_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='designerorder',
            name='total_price',
        ),
    ]
