# Generated by Django 5.2.8 on 2026-02-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0008_remove_designerorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='designer_profiles/'),
        ),
        migrations.AddField(
            model_name='designer',
            name='specialty',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='designer',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
