# Generated by Django 5.2.8 on 2026-02-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_orderitem_properties'),
        ('designers', '0009_designer_banner_image_designer_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=100)),
                ('tracking_status', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='customers.orderitem')),
            ],
        ),
    ]
