# Generated by Django 5.2.8 on 2026-02-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0010_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
