# Generated by Django 5.2.8 on 2026-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0011_designer_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='designer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='designer',
            name='status_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designer',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
