# Generated by Django 5.2.8 on 2026-03-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0012_remove_designer_is_approved_designer_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaAsset',
        ),
    ]
