# Generated by Django 5.2.8 on 2026-03-05 15:02

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0013_delete_mediaasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designer',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designeranalytics',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designerorder',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designerproduct',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designerstory',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryalert',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storyview',
            name='id',
            field=models.CharField(default=apps.core.models.generate_custom_uuid, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
