# Generated by Django 5.2.8 on 2026-03-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_category_id_alter_mediaasset_id_and_more'),
        ('designers', '0015_alter_collection_id_alter_designer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='lookbook_files',
            field=models.ManyToManyField(to='core.mediaasset'),
        ),
    ]
