# Generated by Django 6.0.4 on 2026-05-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='featured_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_designer', to='designers.collection'),
        ),
        migrations.AddField(
            model_name='designer',
            name='is_sustainable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designer',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='{"facebook": "url", "twitter": "url", "tiktok": "url"}'),
        ),
        migrations.AddField(
            model_name='designer',
            name='sustainability_certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications e.g. ["GOTS", "Fair Trade"]'),
        ),
        migrations.AddField(
            model_name='designer',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short brand tagline', max_length=255),
        ),
    ]
