# Generated by Django 6.0.4 on 2026-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0018_designer_featured_collection_designer_is_sustainable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='sustainability_notes',
            field=models.TextField(blank=True, help_text='Free-form notes about sustainability practices'),
        ),
    ]
