# Generated by Django 6.0.4 on 2026-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0019_designer_sustainability_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='city',
            field=models.CharField(blank=True, help_text='City / base of operation', max_length=200),
        ),
        migrations.AddField(
            model_name='designer',
            name='founder_name',
            field=models.CharField(blank=True, help_text='Designer or founder name', max_length=200),
        ),
        migrations.AddField(
            model_name='designer',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone / WhatsApp number', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='price_range',
            field=models.CharField(blank=True, help_text='Average product price range', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='product_count_range',
            field=models.CharField(blank=True, help_text='Products ready to list: 1-5, 6-10, 11-25, 25+', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='production_type',
            field=models.CharField(blank=True, help_text='Ready-to-wear, made-to-order, custom orders, pre-order, mix', max_length=100),
        ),
        migrations.AddField(
            model_name='designer',
            name='ships_internationally',
            field=models.CharField(blank=True, help_text='Yes, No, Not yet but I want to', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='unique_attributes',
            field=models.JSONField(blank=True, default=list, help_text='Brand uniqueness checkboxes e.g. ["handmade", "sustainable"]'),
        ),
    ]
