# Generated by Django 6.0.4 on 2026-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0020_designer_city_designer_founder_name_designer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='storefront_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='upload_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='welcome_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
