# Generated by Django 6.0.4 on 2026-06-03 13:11

from django.db import migrations, models


def convert_specialty_to_json(apps, schema_editor):
    Designer = apps.get_model('designers', 'Designer')
    for designer in Designer.objects.all():
        val = designer.specialty
        if val and isinstance(val, str) and val.strip():
            designer.specialty = [val.strip()]
            designer.save(update_fields=['specialty'])
        elif not val:
            designer.specialty = []
            designer.save(update_fields=['specialty'])


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0021_designer_storefront_reminder_sent_at_and_more'),
    ]

    operations = [
        # Step 1: Convert existing string data to JSON arrays
        migrations.RunPython(convert_specialty_to_json, migrations.RunPython.noop),
        # Step 2: SQLite can't ALTER a CharField to JSONField directly because
        # its table remake checks JSON_VALID against existing rows.
        # Use SeparateDatabaseAndState so Django only records the state change
        # without attempting a table rebuild.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='designer',
                    name='specialty',
                    field=models.JSONField(blank=True, default=list, help_text='List of fashion niches e.g. ["womenswear", "menswear", "accessories"]'),
                ),
            ],
            database_operations=[
                # No-op for SQLite: JSONField stores as TEXT anyway.
                # The data was already converted to valid JSON by RunPython above.
                migrations.RunSQL(
                    sql=migrations.RunSQL.noop,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
