# Generated by Django 6.0.4 on 2026-06-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0022_alter_designer_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='local_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Local shipping fee for domestic orders in designer's country", max_digits=10),
        ),
    ]
