# Generated by Django 6.0.4 on 2026-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0023_designer_local_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
