# Generated by Django 5.2.7 on 2025-11-01 10:41

import apps.utils.uuid_generator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('profile_type', models.CharField(blank=True, default='', max_length=200)),
                ('date_time_added', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('gender', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('profile', models.JSONField(default=dict)),
                ('date_time_added', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('designer', 'Designer'), ('admin', 'Admin')], default='customer', help_text='Defines the role of the user on Urbana platform.', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number with country code (e.g., +234... for Nigeria).', max_length=15, null=True, unique=True)),
                ('bio', models.TextField(blank=True, help_text="Short bio to showcase designer's story or customer's fashion interests.", null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text="Profile image to personalize the user's presence on Urbana.", null=True, upload_to='profile_pics/')),
                ('made_in_country_code', models.CharField(max_length=250)),
                ('made_in_country_name', models.CharField(max_length=250)),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates if the user's email/phone is verified for secure access.")),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.TextField(default='', max_length=5000)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('secret_question', models.CharField(blank=True, default='', max_length=225)),
                ('secret_answer', models.CharField(blank=True, default='', max_length=225)),
                ('previous_email', models.CharField(blank=True, default='', max_length=225)),
                ('last_token', models.CharField(blank=True, default='', max_length=225)),
                ('profile_updated', models.BooleanField(blank=True, default=False)),
                ('suspension_count', models.IntegerField(blank=True, default=0)),
                ('briefly_suspended', models.BooleanField(blank=True, default=False)),
                ('time_suspended', models.DateTimeField(blank=True, null=True)),
                ('time_suspended_timestamp', models.IntegerField(blank=True, default=0)),
                ('locked', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=45)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('two_factor_auth_enabled', models.BooleanField(default=False)),
                ('email_change_request', models.BooleanField(default=False)),
                ('pending_email', models.EmailField(blank=True, default='', max_length=254)),
                ('login_attempt_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.CharField(default=apps.utils.uuid_generator.generate_custom_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('code', models.TextField(default='', max_length=5000)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
