# Generated by Django 6.0.4 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('support_agent', 'Support Agent'), ('product_manager', 'Product Manager'), ('marketer', 'Marketer'), ('c_level', 'C-Level Executive'), ('finance', 'Finance Manager')], help_text="Defines the granular role if the user_type is 'admin'.", max_length=20, null=True),
        ),
    ]
