# Generated by Django 5.2.8 on 2026-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
