# Generated by Django 6.0.4 on 2026-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('support_agent', 'Support Agent'), ('product_manager', 'Product Manager'), ('marketer', 'Marketer'), ('c_level', 'C-Level Executive'), ('finance', 'Finance Manager'), ('risk', 'Risk / Compliance'), ('analyst', 'Analyst'), ('operations', 'Operations Manager'), ('designer_success', 'Designer Success')], help_text="Defines the granular role if the user_type is 'admin'.", max_length=20, null=True),
        ),
    ]
