# Generated by Django 5.2.8 on 2026-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='made_in_country_code',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='made_in_country_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
