# Generated by Django 6.0.4 on 2026-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_made_in_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
