# Generated by Django 6.0.4 on 2026-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_height_user_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
