# Generated by Django 6.0.4 on 2026-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetcode_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('support_agent', 'Support Agent'), ('product_manager', 'Product Manager')], help_text="Defines the granular role if the user_type is 'admin'.", max_length=20, null=True),
        ),
    ]
